name: openhsi_dev
channels:
  - fastai
  - conda-forge
  - nodefaults
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - fastai::nbdev = 1.2.11
  - fastai::fastcore 
  - fastai::fastprogress
  - h5py
  - xarray
  - pillow
  - pandas
  - tqdm
  - bokeh
  - holoviews
  - panel
  - param 
  - pyserial
  - netcdf4
  - Py6S
  - hvplot
  - streamz
  - datashader
  - psutil