name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
        with:
          version: "3.8"
